@startuml 
actor User
left to right direction
skinparam actor{
    FontColor #87acbe
    BackgroundColor #87acbe
    BorderColor #87acbe
    Shadowing false
}
skinparam usecase {
    FontColor White 
    ArrowColor LightCoral
    BackgroundColor LightCoral
    BorderColor LightCoral
    Shadowing false
}
skinparam rectangle{    
    FontColor #394856
    BorderColor #394856
    Shadowing false
}
rectangle "Resident Door Lock Control "{

    User -- (Sign In)
    User -- (Sign Up)
    User -- (Select Door)
    User -- (Control)
    User -- (Report)
    User -- (Change Password)
    User -- (Sign Out)
    
}

@enduml